### ISSUE TITLE
How would I change the color scheme?

### ISSUE THREAD

**Issue by GitHubEmploy** [bchiang7/v4#118]
How would I change the color scheme and/or add google tracking? I would like to change to red and white or black and white.

**Comment by truthteller505** [comment]
Hello,

To change color schemes, I presume you would modify variables at this path:

https://github.com/bchiang7/v4/blob/main/src/styles/GlobalStyle.js

And for google tracking, check this out: https://www.gatsbyjs.com/docs/how-to/adding-common-features/adding-analytics/

**You claim to have an IQ of 217, but your actions show otherwise...**

You state you know 14 programming languages, but you didn't bother to check the file paths on the GitHub page and simply change some initial styling values. Moreover, you took @bchiang7's website and removed any accreditation to her even though it was explicitly specified in the first sentence of the README. You consciously replaced it with _"Designed & Built by Mohit Varikuti."_ The real question is, of what you are trying to accomplish if you are placing a facade in front of your true self. Your projects are impressive, but all I am suggesting is to be wary of what you have online, as it will remain there forever. If something isn't true, you might want to think twice before including it. 

**MOST IMPORTANTLY: It is not good to dox yourself on GitHub and on your personal website. From these two sources, I have literally found 1) where you live 2) what you look like 3) where you go to school and 4) your phone number.**

**For your own good, please make sure to fix this.**

**Comment by truthteller505** [comment]
Please make sure to fix it. It is immeasurably dangerous.

**Comment by GitHubEmploy** [comment]
Ok, thanks for your help.

**Comment by GitHubEmploy** [comment]
Except, the projects page is broken. How would I fix this?
<img width="1128" alt="Screen Shot 2021-01-31 at 1 01 50 AM" src="https://user-images.githubusercontent.com/65371337/106379318-f5188580-635f-11eb-92b4-553e08b18ee0.png">
