### ISSUE TITLE
Why did you choose to create a custom webpack config?

### ISSUE THREAD

**Issue by twhite96** [bchiang7/v4#80]
Hi Brittany! I am currently redesigning my portfolio and am taking cues (not much code) from your portfolio here. I noticed in your `gatsby-node.js` file you have a custom webpack config but I don't understand why someone would do this. I am new to Gatsby and only have 1 year of professional dev experience so I am just trying to grok why one would do this, if my rambling makes any sense.

Thanks for your help.

**Comment by bchiang7** [comment]
Hey @twhite96, I'm assuming you're referring to [`onCreateWebpackConfig`](https://github.com/bchiang7/v4/blob/master/gatsby-node.js#L70). I did this because I'm using two third parties libraries (ScrollReveal and anime.js) that expect `window` to be defined. Since `window` is not defined at build time, Gatsby's solution is [to customize the webpack configuration to replace the offending module with a dummy module during server rendering](https://www.gatsbyjs.org/docs/debugging-html-builds/#fixing-third-party-modules).

**Comment by twhite96** [comment]
@bchiang7 Thanks so much! I didn't know this limitation but appreciate the explanation.

I'll close this out then.
